arm64: Fix CONFIG_64BIT leak to userspace
Commit b4b2ede8d4ca895a792d7feb196a9df8f6d10c35 disabled the use of config
options in uapi headers. Use __aarch64__ which is a compiler-defined
method of obtaining the architecture instead of CONFIG_64BIT.

Fixes the following error:
    error: kernel/google/raviole/arch/arm64/include/uapi/asm/sigcontext.h:
        leak CONFIG_64BIT to user-space

Change-Id: Ie1f22679882acbc3e253316d5281287956a4febd
Signed-off-by: Majaahh <maja.blaszczak@proton.me>